BoooostUp/carone

src/App.jsx

- added PR test template
- added test tempate
- N/A

🧪 Test: added pr request template test code

---

.eslintrc.cjs

- eslint파일에 jsx import도 변경되도록 수정
-
-

♻️ refactor: eslint파일에 jsx import도 변경되도록 수정

---

package-lock.json
package.json
src/App.jsx
src/Router.jsx
src/pages/Carone.jsx
src/pages/Ce.jsx
src/pages/Home.jsx
src/pages/Layout.jsx
src/pages/Root.jsx
src/pages/Sg.jsx
src/pages/Si.jsx
src/pages/Total.jsx

- Added router settings
- N/A
- N/A

✨ Feat: Added DOM-Basic router setting

---

src/styles/utils/mediaQuery.ts

- Added Media Query Type Script file
- Added usage later after adding router
- X

🌱 Feat: Add media query type script file

---

src/components/Footer/FooterExample.jsx
src/components/Header/HeaderExample.jsx
src/components/Main/MainExample.jsx

✨ Feat: Add Component Example Folders

---

.eslintrc.cjs

- eslint rules에 'react/prop-types': 'off' 추가

[초기세팅] eslint rules에 option 추가

---

src/styles/theme.js

[초기세팅] theme의 회사 이름 대문자로 변경

---

src/components/Header/LNB.jsx

- LNB 폴더 삭제 및 상수 불러올 때 toLowerCase 되지 않도록 변경
-
-
-

[컴포넌트] LNB 폴더 삭제 및 상수 불러올 때 toLowerCase 되지 않도록 변경

---

src/components/Main/MainArticle.jsx
src/constants/MAIN_ARTICLE_CONTENTS.js

- 상수 객체 key, value 이름 수정 및 불러올 때 대문자로 불러오도록 수정
- 
- 
-

[컴포넌트] 상수 객체 key, value 이름 수정 및 불러올 때 대문자로 불러오도록 수정

---

src/Router.jsx
src/components/Main/BNB/Bnb.jsx
src/components/Main/BNB/BnbButton.jsx
src/pages/Layout.jsx

- Theme constant 수정 BNB에 적용완료
- N/A
- N/A

[컴포넌트] BNB constant 수정 BNB

---

src/Router.jsx
src/components/Main/SubCategoryBar.jsx

- Add subcategorybar
- 버튼 누르면 토글로 페이지 이동가능하게 설정함
- 이미지만 들어가는거라 크게 건들게 없슴
- N/A

[컴포넌트] Subcategory Bar

---

src/styles/GlobalStyle.js

[컴포넌트] 텍스트 드래그 방지

---

src/App.jsx
src/components/Main/BNB/Bnb.jsx

[컴포넌트] BNB state 활성화 안되는거 수정완

---

src/pages/Carone/Carone.jsx
src/pages/Carone2/Carone2.jsx
src/pages/Ce/Ce.jsx
src/pages/Home/Home.jsx
src/pages/Sg/Sg.jsx
src/pages/Si/Si.jsx
src/pages/Total/Total.jsx
src/pages/Total2/Total2.jsx

- QnA Button 각 페이지 화면에 고정하였습니다.
-
-

[컴포넌트] QnA Button 화면에 고정

---

src/constants/ROOT.js
src/pages/Layout.jsx
src/pages/Root.jsx

- root페이지에서 cell을 눌렀을 때 해당 페이지로 이동 기능 구현
-
-

[컴포넌트] root 페이지 이동 기능 구현

---

src/components/Header/Lnb.jsx

- LNB 보여질 때 밑의 컨텐츠 밀리지 않도록 수정 및 애니메이션 추가
-
-

[컴포넌트] LNB 보여질 때 밑의 컨텐츠 밀리지 않도록 수정 및 애니메이션 추가

---

src/components/Main/Hero.jsx

- Hero 모바일 기능 추가 
- 이미지 어둡게 처리
- 사이즈 크기 수정
- 글씨 크기 수정해야 함
-

[컴포넌트] Hero 모바일 기능 추가

---

src/components/Main/BNB/Bnb.jsx
src/components/Main/BNB/BnbButton.jsx
src/pages/Carone/Carone.jsx
src/pages/Carone2/Carone2.jsx
src/pages/Ce/Ce.jsx
src/pages/Home/Home.jsx
src/pages/Sg/Sg.jsx
src/pages/Si/Si.jsx
src/pages/Total/Total.jsx
src/pages/Total2/Total2.jsx

- Edit minor error
- N/A
- N/A

[컴포넌트] BNB높이수정, 작은에러 수정

---

src/components/Header/Gnb.jsx
src/constants/GNB_CONTENTS.js
src/constants/LNB_CONTENTS.js
src/pages/Carone2/Carone2.jsx
src/pages/Total2/Total2.jsx
src/styles/theme.js

- Gnb 2공장 링크 연결 및 모바일 호버 색 변하는것 방지
-
-

[컴포넌트] Gnb 2공장 링크 연결 및 모바일 호버 색 변하는것 방지

---

src/components/Header/Lnb.jsx

[컴포넌트] LNB 스크롤 시 고정되도록 수정

---

src/components/Main/QnAButton.jsx
src/pages/Carone/Carone.jsx
src/pages/Carone2/Carone2.jsx
src/pages/Ce/Ce.jsx
src/pages/Home/Home.jsx
src/pages/Home/HomeMain.jsx
src/pages/Sg/Sg.jsx
src/pages/Si/Si.jsx
src/pages/Total/Total.jsx
src/pages/Total2/Total2.jsx

- Add article Feat
- Fix Footer BNB UI
-
-

[Feat] Add articles

---

src/components/Main/Hero.jsx

Hero 어두운 화면 위치 조정

---

src/components/Header/Lnb.jsx

[컴포넌트] LNB 컨테이너에 z-index 추가

---

src/components/Main/Hero.jsx
src/components/Main/WelcomeBox.jsx

- WelcomeBox 적용
- Hero 모바일 사이즈 오류 수정
-
-

[컴포넌트] WelcomeBox 적용

---

src/Router/Router.jsx
src/components/Certification/CERTIFICATIONS.js
src/components/Certification/Certificate.jsx
src/components/Certification/CertificateModal.jsx
src/components/Certification/CertificationComponent.jsx
src/components/Main/SubCategoryBar.jsx
src/pages/Carone/CaroneLicenses.jsx

- Add Carone Certifications on page
-
-

✨ Feat: Add certification feature on carone test1

---

src/components/RecruitButton.jsx
src/pages/Root.jsx

- Root페이지 모바일 버전 구현
- 모바일에 맞춰서 index 크기와 글씨 크기 줄였습니다
- 인재 채용 버튼 양 옆 padding 줄였습니다
- 모바일 버전이기 때문에 hover는 적용되지 않습니다
-

[컴포넌트] Root페이지 모바일 버전 구현

---

src/constants/ROOT.js
src/pages/Root.jsx

- 배포 시 이미지가 렌더링 되지 않는 현상 수정
-
-

[컴포넌트] 배포 시 이미지가 렌더링 되지 않는 현상 수정

---

src/constants/INTRO_CONTENT_CONTENTS.js
src/constants/MAIN_ARTICLE_CONTENTS.js
src/pages/Home/HomeBusiness.jsx
src/pages/Home/HomeMain.jsx

- 이미지 파일 Import로 불러오도록 수정
- HOME 페이지에서 MainArticle 불러오는 위치 [홈] -> [사업 분야] 변경
- HOME 페이지에는 원래 보여줘야 할 IntroContent 컴포넌트를 불러오도록 수정했습니다.
-
-

[컴포넌트] 이미지 파일 Import로 불러오도록 수정 및 MainArticle 위치 변경

---

src/components/Header/Gnb.jsx
src/components/Main/CategoryBar.jsx
src/components/Main/SubCategoryBar.jsx
src/pages/Carone/Business/CaroneBusinessLayout.jsx

- Gnb 테블렛 사이즈일때 마우스 오버 하얀색으로 변하는 것 수정 
- 카테고리바 모바일 반응형 구현
-
-

Gnb 마우스 오버 수정 및 카테고리바 모바일 반응형 작업

---

src/components/Main/IntroContent.jsx
src/components/Main/MainArticle.jsx

- 모바일 사이즈일 때 이미지, 텍스트 가로 사이즈 수정
-
-

[컴포넌트] 모바일 사이즈일 때 이미지, 텍스트 가로 사이즈 수정

---

index.html
src/components/Main/CategoryBar.jsx

- 카테고리바 모바일 화면 수정 
- 회사소개, 사업내용에 보이는 화면 다르게 수정
-
-

🐛 Fix: 카테고리바 모바일 화면 수정

---

src/components/Footer/Footer.jsx

[FIX] 💚 Fix: Fix home footer UI

---

src/components/Main/MainArticle.jsx

[컴포넌트] 텍스트 양옆에 padding 추가

---

src/components/Main/Map.jsx
src/constants/MAP_CONTENTS.js
src/pages/Carone2/Info/Carone2InfoLocation.jsx

[컴포넌트] Map 사진 경로 수정

---

src/pages/Carone/CaroneMain.jsx
src/pages/Carone2/Carone2Main.jsx
src/pages/Ce/CeMain.jsx
src/pages/Sg/SgMain.jsx
src/pages/Si/SiMain.jsx
src/pages/Total/TotalMain.jsx
src/pages/Total2/Total2Main.jsx

[Add UI] ⚡️ Feat: Added main page for each companies

---

src/components/Main/QnAModal.jsx
src/pages/Carone/Info/CaroneInfoBusinessPartner.jsx
src/pages/Carone2/Info/Carone2InfoBusinessPartner.jsx
src/pages/Ce/Info/CeInfoBusinessPartner.jsx
src/pages/Sg/Info/SgInfoBusinessPartner.jsx
src/pages/Si/Info/SiInfoBusinessPartner.jsx
src/pages/Total/Info/TotalInfoBusinessPartner.jsx
src/pages/Total2/Info/Total2InfoBusinessPartner.jsx

[컴포넌트] QnA 모달 사이즈 수정

---

src/pages/Carone/CaroneMain.jsx
src/pages/Total/TotalMain.jsx

- 카원, 토탈 1공장에서 홈 페이지 배경색 적용 안되는 부분 수정
-
-

[컴포넌트] 카원, 토탈 1공장에서 홈 페이지 배경색 적용 안되는 부분 수정

---

src/components/Certification/CertificateModal.jsx
src/components/Main/SubCategoryBar.jsx
src/constants/FOOTER_CONTENTS.js

[FIX] 🩹 Fix: fix minor issues

---

src/components/Main/BNB/BnbButton.jsx

[CONE-47] 🎨 Change BNB mobile size

---

.htaccess
package.json
vite.config.js

Fix 404 error for client-side routing

---

src/components/Certification/CERTIFICATIONS.js
src/components/Footer/Footer.jsx
src/pages/Es/EsLicenses/EsLicenses.jsx

[CONE-75] 에너지 스토리 인허가 사항 에러 수정 및 Home페이지 키 중복 오류 수정

---

src/components/Main/BNB/Bnb.jsx
src/components/Main/BNB/BnbButton.jsx
src/constants/FOOTER_CONTENTS.js
src/pages/Es/Es.jsx
src/pages/Hwangji/Hwangji.jsx

- 그리드 수정
- 황지, 에너지스토리 BNB 위치 수정
- 화면 길이에 따라 BNB를 1줄 -> 2줄 -> DropDown 으로 수정
-

[CONE-72] BNB 위치 수정

---

package-lock.json
package.json
src/components/Header/Gnb.jsx
src/components/Main/CategoryBar.jsx
src/components/Main/DashBoard.jsx
src/components/Main/Hero.jsx
src/components/Main/Intro.jsx
src/components/Main/IntroContent.jsx
src/constants/FOOTER_CONTENTS.js
src/constants/GNB_CONTENTS.js
src/constants/HERO_CONTENTS.js
src/pages/Home/Home.jsx
src/pages/Hwangji/Hwangji.jsx
src/styles/theme.js

Hk fix new branch

---

src/components/Main/IntroContent.jsx

[컴포넌트] IntroContent UI 업데이트

---

src/components/Main/CompanyCarousel.jsx
src/components/Main/IntroContent.jsx
src/pages/Home/Home.jsx

[컴포넌트] company carousel 제작

---

package-lock.json
src/components/Main/IntroContent.jsx

- IntroContent 애니메이션 아이템 클릭 후 다음 아이템 클릭하면 타이머가 남아있던 오류 수정
-
-
-

[컴포넌트] IntroContent 애니메이션 작동 수정

---

src/components/Main/MainInfo.jsx
src/components/Main/Partners/Partners.jsx

Fix: 회사소개 상단, 하단 컴포넌트 모바일 반응형 UI

---

src/components/Main/DashBoard.jsx

change dashboard font size

---

package-lock.json
package.json
src/components/Main/MainInfo.jsx
src/components/Main/Partners/Partners.jsx

- 아래에서 위로 올라갈때 애니메이션 적용 안되게 수정
- 모바일 사이즈 수정
-
-

[컴포넌트] main 상단, 하단 UI, 동작 수정

---

src/components/Main/MainInfo.jsx
src/components/Main/Partners/Partners.jsx

[컴포넌트] main info, partners CSS 수정
